#!/usr/bin/env bash

echo "nameserver 1.1.1.1" >  /etc/resolv.conf
echo "nameserver 1.0.0.1" >> /etc/resolv.conf

HOST_USERNAME=${ENV_USER:-user}
HOST_USERID=${ENV_USER_UID:-9999}

useradd -m -s /bin/bash -u ${HOST_USERID} ${HOST_USERNAME}

echo "${HOST_USERNAME}:resu" | chpasswd > /dev/null 2>&1
echo "${HOST_USERNAME}    ALL=(ALL) ALL" >> /etc/sudoers

find /opt/dotfiles/ -type f -maxdepth 1 -exec ln -s {} /home/${HOST_USERNAME}/ \; > /dev/null 2>&1
ln -s /opt/dotfiles/.vim /home/${HOST_USERNAME}/
echo ". /opt/dotfiles/.danarchy" >> /home/${HOST_USERNAME}/.profile

chown -R ${HOST_USERNAME}:${HOST_USERNAME} /home/${HOST_USERNAME}
su - ${HOST_USERNAME}